from roombeacon_crawler.demo.sources.nhatot.selectors import (
    AREA_CLASSES,
    CARD_CONTAINER_CLASSES,
    CARD_CONTAINER_TESTIDS,
    LOCATION_CLASSES,
    MAIN_CONTAINER_CLASSES,
    MAIN_CONTAINER_TESTIDS,
    PRICE_CLASSES,
    TITLE_CLASSES,
)

__all__ = [
    "MAIN_CONTAINER_CLASSES",
    "MAIN_CONTAINER_TESTIDS",
    "CARD_CONTAINER_CLASSES",
    "CARD_CONTAINER_TESTIDS",
    "TITLE_CLASSES",
    "PRICE_CLASSES",
    "AREA_CLASSES",
    "LOCATION_CLASSES",
]
