"""Dữ liệu đối chiếu đơn vị hành chính cũ sang phường hiện hành."""

WARD_MAPPING: dict[str, list[str]] = {
    # Quận 1
    "ben nghe": ["Phường Sài Gòn"],
    "ben nghe quan 1": ["Phường Sài Gòn"],
    "da kao": ["Phường Sài Gòn", "Phường Tân Định"],
    "da kao quan 1": ["Phường Sài Gòn", "Phường Tân Định"],
    "nguyen thai binh": ["Phường Sài Gòn", "Phường Bến Thành"],
    "nguyen thai binh quan 1": ["Phường Sài Gòn", "Phường Bến Thành"],
    "tan dinh": ["Phường Tân Định"],
    "tan dinh quan 1": ["Phường Tân Định"],
    "ben thanh": ["Phường Bến Thành"],
    "ben thanh quan 1": ["Phường Bến Thành"],
    "pham ngu lao": ["Phường Bến Thành"],
    "pham ngu lao quan 1": ["Phường Bến Thành"],
    "cau ong lanh": ["Phường Bến Thành", "Phường Cầu Ông Lãnh"],
    "cau ong lanh quan 1": ["Phường Bến Thành", "Phường Cầu Ông Lãnh"],
    "nguyen cu trinh": ["Phường Cầu Ông Lãnh"],
    "nguyen cu trinh quan 1": ["Phường Cầu Ông Lãnh"],
    "cau kho": ["Phường Cầu Ông Lãnh"],
    "cau kho quan 1": ["Phường Cầu Ông Lãnh"],
    "co giang": ["Phường Cầu Ông Lãnh"],
    "co giang quan 1": ["Phường Cầu Ông Lãnh"],

    # Quận 3
    "1 quan 3": ["Phường Bàn Cờ"],
    "2 quan 3": ["Phường Bàn Cờ"],
    "3 quan 3": ["Phường Bàn Cờ"],
    "4 quan 3": ["Phường Bàn Cờ", "Phường Xuân Hòa"],
    "5 quan 3": ["Phường Bàn Cờ"],
    "vo thi sau": ["Phường Xuân Hòa"],
    "vo thi sau quan 3": ["Phường Xuân Hòa"],
    "9 quan 3": ["Phường Nhiêu Lộc"],
    "11 quan 3": ["Phường Nhiêu Lộc"],
    "12 quan 3": ["Phường Nhiêu Lộc"],
    "14 quan 3": ["Phường Nhiêu Lộc"],

    # Quận 4
    "1 quan 4": ["Phường Vĩnh Hội"],
    "2 quan 4": ["Phường Khánh Hội", "Phường Vĩnh Hội"],
    "3 quan 4": ["Phường Vĩnh Hội"],
    "4 quan 4": ["Phường Khánh Hội", "Phường Vĩnh Hội"],
    "8 quan 4": ["Phường Khánh Hội"],
    "9 quan 4": ["Phường Khánh Hội"],
    "13 quan 4": ["Phường Xóm Chiếu"],
    "15 quan 4": ["Phường Xóm Chiếu", "Phường Khánh Hội"],
    "16 quan 4": ["Phường Xóm Chiếu"],
    "18 quan 4": ["Phường Xóm Chiếu"],

    # Quận 5
    "1 quan 5": ["Phường Chợ Quán"],
    "2 quan 5": ["Phường Chợ Quán"],
    "4 quan 5": ["Phường Chợ Quán"],
    "5 quan 5": ["Phường An Đông"],
    "7 quan 5": ["Phường An Đông"],
    "9 quan 5": ["Phường An Đông"],
    "11 quan 5": ["Phường Chợ Lớn"],
    "12 quan 5": ["Phường Chợ Lớn"],
    "13 quan 5": ["Phường Chợ Lớn"],
    "14 quan 5": ["Phường Chợ Lớn"],

    # Quận 6
    "1 quan 6": ["Phường Bình Tiên"],
    "2 quan 6": ["Phường Bình Tây"],
    "7 quan 6": ["Phường Bình Tiên"],
    "8 quan 6": ["Phường Bình Tiên"],
    "9 quan 6": ["Phường Bình Tây"],
    "10 quan 6": ["Phường Bình Phú"],
    "11 quan 6": ["Phường Bình Phú"],
    "12 quan 6": ["Phường Phú Lâm"],
    "13 quan 6": ["Phường Phú Lâm"],
    "14 quan 6": ["Phường Phú Lâm"],

    # Quận 7
    "binh thuan": ["Phường Tân Thuận"],
    "binh thuan quan 7": ["Phường Tân Thuận"],
    "tan thuan dong": ["Phường Tân Thuận"],
    "tan thuan dong quan 7": ["Phường Tân Thuận"],
    "tan thuan tay": ["Phường Tân Thuận"],
    "tan thuan tay quan 7": ["Phường Tân Thuận"],
    "phu thuan": ["Phường Phú Thuận"],
    "phu thuan quan 7": ["Phường Phú Thuận"],
    "phu my": ["Phường Phú Thuận", "Phường Tân Mỹ"],
    "phu my quan 7": ["Phường Phú Thuận", "Phường Tân Mỹ"],
    "tan phu": ["Phường Tân Mỹ"],
    "tan phu quan 7": ["Phường Tân Mỹ"],
    "tan phong": ["Phường Tân Hưng"],
    "tan phong quan 7": ["Phường Tân Hưng"],
    "tan quy": ["Phường Tân Hưng"],
    "tan quy quan 7": ["Phường Tân Hưng"],
    "tan kieng": ["Phường Tân Hưng"],
    "tan kieng quan 7": ["Phường Tân Hưng"],
    "tan hung": ["Phường Tân Hưng"],
    "tan hung quan 7": ["Phường Tân Hưng"],

    # Quận 8
    "4 quan 8": ["Phường Chánh Hưng"],
    "5 quan 8": ["Phường Chánh Hưng", "Phường Bình Đông"],
    "6 quan 8": ["Phường Bình Đông"],
    "7 quan 8": ["Phường Bình Đông", "Phường Bình Hưng"],
    "14 quan 8": ["Phường Phú Định"],
    "15 quan 8": ["Phường Phú Định"],
    "16 quan 8": ["Phường Phú Định", "Phường Bình Phú", "Phường Tân Nhựt"],
    "rach ong": ["Phường Chánh Hưng"],
    "rach ong quan 8": ["Phường Chánh Hưng"],
    "hung phu": ["Phường Chánh Hưng"],
    "hung phu quan 8": ["Phường Chánh Hưng"],
    "xom cui": ["Phường Phú Định"],
    "xom cui quan 8": ["Phường Phú Định"],

    # Quận 10
    "1 quan 10": ["Phường Vườn Lài"],
    "2 quan 10": ["Phường Vườn Lài"],
    "4 quan 10": ["Phường Vườn Lài"],
    "6 quan 10": ["Phường Diên Hồng"],
    "8 quan 10": ["Phường Diên Hồng"],
    "9 quan 10": ["Phường Vườn Lài"],
    "10 quan 10": ["Phường Vườn Lài"],
    "12 quan 10": ["Phường Hòa Hưng"],
    "13 quan 10": ["Phường Hòa Hưng"],
    "14 quan 10": ["Phường Diên Hồng", "Phường Hòa Hưng"],
    "15 quan 10": ["Phường Hòa Hưng"],

    # Quận 11
    "1 quan 11": ["Phường Minh Phụng"],
    "3 quan 11": ["Phường Bình Thới"],
    "5 quan 11": ["Phường Hòa Bình"],
    "7 quan 11": ["Phường Minh Phụng"],
    "8 quan 11": ["Phường Bình Thới", "Phường Phú Thọ"],
    "10 quan 11": ["Phường Bình Thới"],
    "11 quan 11": ["Phường Phú Thọ"],
    "14 quan 11": ["Phường Hòa Bình"],
    "15 quan 11": ["Phường Phú Thọ"],
    "16 quan 11": ["Phường Minh Phụng"],

    # Quận 12
    "tan thoi nhat": ["Phường Đông Hưng Thuận"],
    "tan thoi nhat quan 12": ["Phường Đông Hưng Thuận"],
    "tan hung thuan": ["Phường Đông Hưng Thuận"],
    "tan hung thuan quan 12": ["Phường Đông Hưng Thuận"],
    "dong hung thuan": ["Phường Đông Hưng Thuận"],
    "dong hung thuan quan 12": ["Phường Đông Hưng Thuận"],
    "tan chanh hiep": ["Phường Trung Mỹ Tây"],
    "tan chanh hiep quan 12": ["Phường Trung Mỹ Tây"],
    "trung my tay": ["Phường Trung Mỹ Tây"],
    "trung my tay quan 12": ["Phường Trung Mỹ Tây"],
    "hiep thanh": ["Phường Tân Thới Hiệp"],
    "hiep thanh quan 12": ["Phường Tân Thới Hiệp"],
    "tan thoi hiep": ["Phường Tân Thới Hiệp"],
    "tan thoi hiep quan 12": ["Phường Tân Thới Hiệp"],
    "thanh xuan": ["Phường Thới An"],
    "thanh xuan quan 12": ["Phường Thới An"],
    "thoi an": ["Phường Thới An"],
    "thoi an quan 12": ["Phường Thới An"],
    "thanh loc": ["Phường An Phú Đông"],
    "thanh loc quan 12": ["Phường An Phú Đông"],
    "an phu dong": ["Phường An Phú Đông"],
    "an phu dong quan 12": ["Phường An Phú Đông"],

    # Bình Tân
    "binh tri dong": ["Phường Bình Trị Đông"],
    "binh tri dong quan binh tan": ["Phường Bình Trị Đông"],
    "binh tri dong a": ["Phường Bình Tân", "Phường Bình Trị Đông"],
    "binh tri dong a quan binh tan": ["Phường Bình Tân", "Phường Bình Trị Đông"],
    "binh tri dong b": ["Phường An Lạc"],
    "binh tri dong b quan binh tan": ["Phường An Lạc"],
    "an lac": ["Phường An Lạc"],
    "an lac quan binh tan": ["Phường An Lạc"],
    "an lac a": ["Phường An Lạc"],
    "an lac a quan binh tan": ["Phường An Lạc"],
    "binh hung hoa": ["Phường Bình Hưng Hòa"],
    "binh hung hoa quan binh tan": ["Phường Bình Hưng Hòa"],
    "binh hung hoa a": ["Phường Bình Trị Đông", "Phường Bình Hưng Hòa"],
    "binh hung hoa a quan binh tan": ["Phường Bình Trị Đông", "Phường Bình Hưng Hòa"],
    "binh hung hoa b": ["Phường Bình Tân"],
    "binh hung hoa b quan binh tan": ["Phường Bình Tân"],
    "tan tao": ["Phường Bình Tân", "Phường Tân Tạo"],
    "tan tao quan binh tan": ["Phường Bình Tân", "Phường Tân Tạo"],
    "tan tao a": ["Phường Tân Tạo", "Phường Tân Nhựt"],
    "tan tao a quan binh tan": ["Phường Tân Tạo", "Phường Tân Nhựt"],
    "tan kien": ["Phường Tân Tạo", "Phường Tân Nhựt"],

    # Tân Phú
    "son ky": ["Phường Bình Hưng Hòa", "Phường Tây Thạnh", "Phường Tân Sơn Nhì"],
    "son ky quan tan phu": ["Phường Bình Hưng Hòa", "Phường Tây Thạnh", "Phường Tân Sơn Nhì"],
    "tay thanh": ["Phường Tây Thạnh"],
    "tay thanh quan tan phu": ["Phường Tây Thạnh"],
    "phu tho hoa": ["Phường Phú Thọ Hòa"],
    "phu tho hoa quan tan phu": ["Phường Phú Thọ Hòa"],
    "tan son nhi": ["Phường Tân Sơn Nhì"],
    "tan son nhi quan tan phu": ["Phường Tân Sơn Nhì"],
    "tan quy quan tan phu": ["Phường Tân Sơn Nhì", "Phường Phú Thọ Hòa"],
    "tan thanh": ["Phường Tân Sơn Nhì", "Phường Phú Thọ Hòa", "Phường Tân Phú"],
    "tan thanh quan tan phu": ["Phường Tân Sơn Nhì", "Phường Phú Thọ Hòa", "Phường Tân Phú"],
    "phu trung": ["Phường Tân Phú"],
    "phu trung quan tan phu": ["Phường Tân Phú"],
    "hoa thanh": ["Phường Tân Phú"],
    "hoa thanh quan tan phu": ["Phường Tân Phú"],
    "tan thoi hoa": ["Phường Tân Phú", "Phường Phú Thạnh"],
    "tan thoi hoa quan tan phu": ["Phường Tân Phú", "Phường Phú Thạnh"],
    "hiep tan": ["Phường Phú Thạnh"],
    "hiep tan quan tan phu": ["Phường Phú Thạnh"],
    "phu thanh": ["Phường Phú Thạnh"],
    "phu thanh quan tan phu": ["Phường Phú Thạnh"],

    # Bình Thạnh
    "1 quan binh thanh": ["Phường Gia Định"],
    "2 quan binh thanh": ["Phường Gia Định"],
    "7 quan binh thanh": ["Phường Gia Định"],
    "17 quan binh thanh": ["Phường Gia Định"],
    "5 quan binh thanh": ["Phường Bình Lợi Trung"],
    "11 quan binh thanh": ["Phường Bình Lợi Trung"],
    "13 quan binh thanh": ["Phường Bình Lợi Trung"],
    "12 quan binh thanh": ["Phường Bình Thạnh"],
    "14 quan binh thanh": ["Phường Bình Thạnh"],
    "26 quan binh thanh": ["Phường Bình Thạnh"],
    "19 quan binh thanh": ["Phường Thạnh Mỹ Tây"],
    "22 quan binh thanh": ["Phường Thạnh Mỹ Tây"],
    "25 quan binh thanh": ["Phường Thạnh Mỹ Tây"],
    "27 quan binh thanh": ["Phường Bình Quới"],
    "28 quan binh thanh": ["Phường Bình Quới"],

    # Gò Vấp
    "1 quan go vap": ["Phường Hạnh Thông"],
    "3 quan go vap": ["Phường Hạnh Thông"],
    "5 quan go vap": ["Phường An Nhơn"],
    "6 quan go vap": ["Phường An Nhơn"],
    "8 quan go vap": ["Phường Thông Tây Hội"],
    "10 quan go vap": ["Phường Gò Vấp"],
    "11 quan go vap": ["Phường Thông Tây Hội"],
    "12 quan go vap": ["Phường An Hội Tây"],
    "14 quan go vap": ["Phường An Hội Tây"],
    "15 quan go vap": ["Phường An Hội Đông"],
    "16 quan go vap": ["Phường An Hội Đông"],
    "17 quan go vap": ["Phường Gò Vấp"],

    # Phú Nhuận
    "1 quan phu nhuan": ["Phường Cầu Kiệu"],
    "2 quan phu nhuan": ["Phường Cầu Kiệu"],
    "4 quan phu nhuan": ["Phường Đức Nhuận"],
    "5 quan phu nhuan": ["Phường Đức Nhuận"],
    "7 quan phu nhuan": ["Phường Cầu Kiệu"],
    "8 quan phu nhuan": ["Phường Phú Nhuận"],
    "9 quan phu nhuan": ["Phường Đức Nhuận"],
    "10 quan phu nhuan": ["Phường Phú Nhuận"],
    "11 quan phu nhuan": ["Phường Phú Nhuận"],
    "13 quan phu nhuan": ["Phường Phú Nhuận"],
    "15 quan phu nhuan": ["Phường Cầu Kiệu", "Phường Phú Nhuận"],

    # Tân Bình
    "1 quan tan binh": ["Phường Tân Sơn Hòa"],
    "2 quan tan binh": ["Phường Tân Sơn Hòa"],
    "3 quan tan binh": ["Phường Tân Sơn Hòa"],
    "4 quan tan binh": ["Phường Tân Sơn Nhất"],
    "5 quan tan binh": ["Phường Tân Sơn Nhất"],
    "6 quan tan binh": ["Phường Tân Hòa"],
    "7 quan tan binh": ["Phường Tân Sơn Nhất"],
    "8 quan tan binh": ["Phường Tân Hòa"],
    "9 quan tan binh": ["Phường Tân Hòa"],
    "10 quan tan binh": ["Phường Bảy Hiền"],
    "11 quan tan binh": ["Phường Bảy Hiền"],
    "12 quan tan binh": ["Phường Bảy Hiền"],
    "13 quan tan binh": ["Phường Tân Bình"],
    "14 quan tan binh": ["Phường Tân Bình"],
    "15 quan tan binh": ["Phường Tân Bình", "Phường Tân Sơn"],

    # Thủ Đức
    "hiep binh chanh": ["Phường Hiệp Bình"],
    "hiep binh phuoc": ["Phường Hiệp Bình"],
    "linh dong": ["Phường Hiệp Bình", "Phường Thủ Đức"],
    "binh tho": ["Phường Thủ Đức"],
    "linh chieu": ["Phường Thủ Đức"],
    "truong tho": ["Phường Thủ Đức"],
    "linh tay": ["Phường Thủ Đức", "Phường Linh Xuân"],
    "binh chieu": ["Phường Tam Bình"],
    "binh chieu thu duc": ["Phường Tam Bình"],
    "tam phu": ["Phường Tam Bình"],
    "tam phu thu duc": ["Phường Tam Bình"],
    "tam binh": ["Phường Tam Bình"],
    "tam binh thu duc": ["Phường Tam Bình"],
    "linh trung": ["Phường Linh Xuân"],
    "linh xuan": ["Phường Linh Xuân"],
    "tan phu thu duc": ["Phường Tăng Nhơn Phú"],
    "hiep phu": ["Phường Tăng Nhơn Phú"],
    "tang nhon phu a": ["Phường Tăng Nhơn Phú"],
    "tang nhon phu b": ["Phường Tăng Nhơn Phú"],
    "long thanh my": ["Phường Tăng Nhơn Phú", "Phường Long Bình"],
    "long binh": ["Phường Long Bình"],
    "truong thanh": ["Phường Long Phước"],
    "truong thanh thu duc": ["Phường Long Phước"],
    "long phuoc": ["Phường Long Phước"],
    "long phuoc thu duc": ["Phường Long Phước"],
    "phu huu": ["Phường Long Trường"],
    "phu huu thu duc": ["Phường Long Trường"],
    "long truong": ["Phường Long Trường"],
    "long truong thu duc": ["Phường Long Trường"],
    "thanh my loi": ["Phường Cát Lái"],
    "thanh my loi thu duc": ["Phường Cát Lái"],
    "cat lai": ["Phường Cát Lái"],
    "cat lai thu duc": ["Phường Cát Lái"],
    "binh trung dong": ["Phường Bình Trưng"],
    "binh trung tay": ["Phường Bình Trưng"],
    "an phu thu duc": ["Phường Bình Trưng", "Phường An Khánh"],
    "phuoc binh": ["Phường Phước Long"],
    "phuoc binh thu duc": ["Phường Phước Long"],
    "phuoc long a": ["Phường Phước Long"],
    "phuoc long a thu duc": ["Phường Phước Long"],
    "phuoc long b": ["Phường Phước Long"],
    "phuoc long b thu duc": ["Phường Phước Long"],
    "thu thiem": ["Phường An Khánh"],
    "an loi dong": ["Phường An Khánh"],
    "thao dien": ["Phường An Khánh"],
    "an khanh": ["Phường An Khánh"],

    # Vũng Tàu
    "1 vung tau": ["Phường Vũng Tàu"],
    "2 vung tau": ["Phường Vũng Tàu"],
    "3 vung tau": ["Phường Vũng Tàu"],
    "4 vung tau": ["Phường Vũng Tàu"],
    "5 vung tau": ["Phường Vũng Tàu"],
    "thang nhi": ["Phường Vũng Tàu"],
    "thang nhi vung tau": ["Phường Vũng Tàu"],
    "thang tam": ["Phường Vũng Tàu"],
    "thang tam vung tau": ["Phường Vũng Tàu"],
    "7 vung tau": ["Phường Tam Thắng"],
    "8 vung tau": ["Phường Tam Thắng"],
    "9 vung tau": ["Phường Tam Thắng"],
    "nguyen an ninh": ["Phường Tam Thắng"],
    "nguyen an ninh vung tau": ["Phường Tam Thắng"],
    "10 vung tau": ["Phường Rạch Dừa"],
    "thang nhat": ["Phường Rạch Dừa"],
    "thang nhat vung tau": ["Phường Rạch Dừa"],
    "rach dua": ["Phường Rạch Dừa"],
    "rach dua vung tau": ["Phường Rạch Dừa"],
    "11 vung tau": ["Phường Phước Thắng"],
    "12 vung tau": ["Phường Phước Thắng"],

    # Quận 1
"pham ngu lao": ["Phường Bến Thành"],
"pham ngu lao quan 1": ["Phường Bến Thành"],
"da kao": ["Phường Sài Gòn", "Phường Tân Định"],
"da kao quan 1": ["Phường Sài Gòn", "Phường Tân Định"],
"ben nghe": ["Phường Sài Gòn"],
"ben nghe quan 1": ["Phường Sài Gòn"],

# Quận 7
"tan phu quan 7": ["Phường Tân Mỹ"],
"tan phu": ["Phường Tân Mỹ"],

# Thủ Đức (Quận 9 cũ)
"phuoc binh": ["Phường Phước Long"],
"phuoc binh quan 9": ["Phường Phước Long"],
"phuoc binh thu duc": ["Phường Phước Long"],
"tang nhon phu b": ["Phường Tăng Nhơn Phú"],
"tang nhon phu a": ["Phường Tăng Nhơn Phú"],
"tang nhon phu": ["Phường Tăng Nhơn Phú"],
"tang nhon phu b quan 9": ["Phường Tăng Nhơn Phú"],
"tang nhon phu a quan 9": ["Phường Tăng Nhơn Phú"],
}
