EXACT_WARD_MAPPING = {
    ("Bình Thuận", "Quận 7"): "Tân Thuận",
    ("Tân Thuận Đông", "Quận 7"): "Tân Thuận",
    ("Tân Thuận Tây", "Quận 7"): "Tân Thuận",
    ("Tân Phong", "Quận 7"): "Tân Hưng",
    ("Tân Quy", "Quận 7"): "Tân Hưng",
    ("Tân Kiểng", "Quận 7"): "Tân Hưng",
    ("Tân Hưng", "Quận 7"): "Tân Hưng",

    ("1", "Quận 5"): "Chợ Quán",
    ("2", "Quận 5"): "Chợ Quán",
    ("4", "Quận 5"): "Chợ Quán",
    ("5", "Quận 5"): "An Đông",
    ("7", "Quận 5"): "An Đông",
    ("9", "Quận 5"): "An Đông",
    ("11", "Quận 5"): "Chợ Lớn",
    ("12", "Quận 5"): "Chợ Lớn",
    ("13", "Quận 5"): "Chợ Lớn",
    ("14", "Quận 5"): "Chợ Lớn",

    ("2", "Quận 6"): "Bình Tây",
    ("9", "Quận 6"): "Bình Tây",
    ("1", "Quận 6"): "Bình Tiên",
    ("7", "Quận 6"): "Bình Tiên",
    ("8", "Quận 6"): "Bình Tiên",
    ("12", "Quận 6"): "Phú Lâm",
    ("13", "Quận 6"): "Phú Lâm",
    ("14", "Quận 6"): "Phú Lâm",

    ("1", "Quận 10"): "Vườn Lài",
    ("2", "Quận 10"): "Vườn Lài",
    ("4", "Quận 10"): "Vườn Lài",
    ("9", "Quận 10"): "Vườn Lài",
    ("10", "Quận 10"): "Vườn Lài",
    ("12", "Quận 10"): "Hòa Hưng",
    ("13", "Quận 10"): "Hòa Hưng",
    ("15", "Quận 10"): "Hòa Hưng",

    ("1", "Quận 11"): "Minh Phụng",
    ("7", "Quận 11"): "Minh Phụng",
    ("16", "Quận 11"): "Minh Phụng",
    ("5", "Quận 11"): "Hòa Bình",
    ("14", "Quận 11"): "Hòa Bình",

    ("Tân Thới Nhất", "Quận 12"): "Đông Hưng Thuận",
    ("Tân Hưng Thuận", "Quận 12"): "Đông Hưng Thuận",
    ("Đông Hưng Thuận", "Quận 12"): "Đông Hưng Thuận",
    ("Tân Chánh Hiệp", "Quận 12"): "Trung Mỹ Tây",
    ("Trung Mỹ Tây", "Quận 12"): "Trung Mỹ Tây",
    ("Hiệp Thành", "Quận 12"): "Tân Thới Hiệp",
    ("Tân Thới Hiệp", "Quận 12"): "Tân Thới Hiệp",
    ("Thạnh Xuân", "Quận 12"): "Thới An",
    ("Thới An", "Quận 12"): "Thới An",
    ("Thạnh Lộc", "Quận 12"): "An Phú Đông",
    ("An Phú Đông", "Quận 12"): "An Phú Đông",

    ("1", "Quận Bình Thạnh"): "Gia Định",
    ("2", "Quận Bình Thạnh"): "Gia Định",
    ("7", "Quận Bình Thạnh"): "Gia Định",
    ("17", "Quận Bình Thạnh"): "Gia Định",
    ("12", "Quận Bình Thạnh"): "Bình Thạnh",
    ("14", "Quận Bình Thạnh"): "Bình Thạnh",
    ("26", "Quận Bình Thạnh"): "Bình Thạnh",
    ("5", "Quận Bình Thạnh"): "Bình Lợi Trung",
    ("11", "Quận Bình Thạnh"): "Bình Lợi Trung",
    ("13", "Quận Bình Thạnh"): "Bình Lợi Trung",
    ("19", "Quận Bình Thạnh"): "Thạnh Mỹ Tây",
    ("22", "Quận Bình Thạnh"): "Thạnh Mỹ Tây",
    ("25", "Quận Bình Thạnh"): "Thạnh Mỹ Tây",
    ("27", "Quận Bình Thạnh"): "Bình Quới",
    ("28", "Quận Bình Thạnh"): "Bình Quới",

    ("1", "Quận Gò Vấp"): "Hạnh Thông",
    ("3", "Quận Gò Vấp"): "Hạnh Thông",
    ("5", "Quận Gò Vấp"): "An Nhơn",
    ("6", "Quận Gò Vấp"): "An Nhơn",
    ("10", "Quận Gò Vấp"): "Gò Vấp",
    ("17", "Quận Gò Vấp"): "Gò Vấp",
    ("15", "Quận Gò Vấp"): "An Hội Đông",
    ("16", "Quận Gò Vấp"): "An Hội Đông",
    ("8", "Quận Gò Vấp"): "Thông Tây Hội",
    ("11", "Quận Gò Vấp"): "Thông Tây Hội",
    ("12", "Quận Gò Vấp"): "An Hội Tây",
    ("14", "Quận Gò Vấp"): "An Hội Tây",

    ("4", "Quận Phú Nhuận"): "Đức Nhuận",
    ("5", "Quận Phú Nhuận"): "Đức Nhuận",
    ("9", "Quận Phú Nhuận"): "Đức Nhuận",

    ("1", "Quận Tân Bình"): "Tân Sơn Hòa",
    ("2", "Quận Tân Bình"): "Tân Sơn Hòa",
    ("3", "Quận Tân Bình"): "Tân Sơn Hòa",
    ("4", "Quận Tân Bình"): "Tân Sơn Nhất",
    ("5", "Quận Tân Bình"): "Tân Sơn Nhất",
    ("7", "Quận Tân Bình"): "Tân Sơn Nhất",
    ("6", "Quận Tân Bình"): "Tân Hòa",
    ("8", "Quận Tân Bình"): "Tân Hòa",
    ("9", "Quận Tân Bình"): "Tân Hòa",
    ("10", "Quận Tân Bình"): "Bảy Hiền",
    ("11", "Quận Tân Bình"): "Bảy Hiền",
    ("12", "Quận Tân Bình"): "Bảy Hiền",

    ("Bình Chiểu", "Thành Phố Thủ Đức"): "Tam Bình",
    ("Tam Phú", "Thành Phố Thủ Đức"): "Tam Bình",
    ("Tam Bình", "Thành Phố Thủ Đức"): "Tam Bình",
    ("Trường Thạnh", "Thành Phố Thủ Đức"): "Long Phước",
    ("Long Phước", "Thành Phố Thủ Đức"): "Long Phước",
    ("Phú Hữu", "Thành Phố Thủ Đức"): "Long Trường",
    ("Long Trường", "Thành Phố Thủ Đức"): "Long Trường",
    ("Thạnh Mỹ Lợi", "Thành Phố Thủ Đức"): "Cát Lái",
    ("Cát Lái", "Thành Phố Thủ Đức"): "Cát Lái",
    ("Phước Bình", "Thành Phố Thủ Đức"): "Phước Long",
    ("Phước Long A", "Thành Phố Thủ Đức"): "Phước Long",
    ("Phước Long B", "Thành Phố Thủ Đức"): "Phước Long",

    ("1", "Thành Phố Vũng Tàu"): "Vũng Tàu",
    ("2", "Thành Phố Vũng Tàu"): "Vũng Tàu",
    ("3", "Thành Phố Vũng Tàu"): "Vũng Tàu",
    ("4", "Thành Phố Vũng Tàu"): "Vũng Tàu",
    ("5", "Thành Phố Vũng Tàu"): "Vũng Tàu",
    ("Thắng Nhì", "Thành Phố Vũng Tàu"): "Vũng Tàu",
    ("Thắng Tam", "Thành Phố Vũng Tàu"): "Vũng Tàu",
    ("7", "Thành Phố Vũng Tàu"): "Tam Thắng",
    ("8", "Thành Phố Vũng Tàu"): "Tam Thắng",
    ("9", "Thành Phố Vũng Tàu"): "Tam Thắng",
    ("Nguyễn An Ninh", "Thành Phố Vũng Tàu"): "Tam Thắng",
    ("10", "Thành Phố Vũng Tàu"): "Rạch Dừa",
    ("Thắng Nhất", "Thành Phố Vũng Tàu"): "Rạch Dừa",
    ("Rạch Dừa", "Thành Phố Vũng Tàu"): "Rạch Dừa",
    ("11", "Thành Phố Vũng Tàu"): "Phước Thắng",
    ("12", "Thành Phố Vũng Tàu"): "Phước Thắng",
}