MERGED_WARDS = {
    "Phường Sài Gòn": {"district": "UNKNOWN_DISTRICT", "aliases": ["Bến Nghé", "Nguyễn Thái Bình", "Phường Sài Gòn", "Sài Gòn", "Đa Kao"]},
    "Phường Tân Định": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phường Tân Định", "Tân Định", "Đa Kao"]},
    "Phường Bến Thành": {"district": "UNKNOWN_DISTRICT", "aliases": ["Bến Thành", "Cầu Ông Lãnh", "Nguyễn Thái Bình", "Phường Bến Thành", "Phạm Ngũ Lão"]},
    "Phường Cầu Ông Lãnh": {"district": "UNKNOWN_DISTRICT", "aliases": ["Cô Giang", "Cầu Kho", "Cầu Ông Lãnh", "Nguyễn Cư Trinh", "Phường Cầu Ông Lãnh"]},
    "Phường Bàn Cờ": {"district": "Quận 3", "aliases": ["Bàn Cờ", "Phường 1", "Phường 2", "Phường 3", "Phường 4", "Phường 5", "Phường Bàn Cờ"]},
    "Phường Xuân Hòa": {"district": "Quận 3", "aliases": ["Phường 4", "Phường Xuân Hòa", "Võ Thị Sáu", "Xuân Hòa"]},
    "Phường Nhiêu Lộc": {"district": "Quận 3", "aliases": ["Nhiêu Lộc", "Phường 11", "Phường 12", "Phường 14", "Phường 9", "Phường Nhiêu Lộc"]},
    "Phường Xóm Chiếu": {"district": "Quận 4", "aliases": ["Phường 13", "Phường 15", "Phường 16", "Phường 18", "Phường Xóm Chiếu", "Xóm Chiếu"]},
    "Phường Khánh Hội": {"district": "Quận 4", "aliases": ["Khánh Hội", "Phường 15", "Phường 2", "Phường 4", "Phường 8", "Phường 9", "Phường Khánh Hội"]},
    "Phường Vĩnh Hội": {"district": "Quận 4", "aliases": ["Phường 1", "Phường 2", "Phường 3", "Phường 4", "Phường Vĩnh Hội", "Vĩnh Hội"]},
    "Phường Chợ Quán": {"district": "Quận 5", "aliases": ["Chợ Quán", "Phường 1", "Phường 2", "Phường 4", "Phường Chợ Quán"]},
    "Phường An Đông": {"district": "Quận 5", "aliases": ["An Đông", "Phường 5", "Phường 7", "Phường 9", "Phường An Đông"]},
    "Phường Chợ Lớn": {"district": "Quận 5", "aliases": ["Chợ Lớn", "Phường 11", "Phường 12", "Phường 13", "Phường 14", "Phường Chợ Lớn"]},
    "Phường Bình Tây": {"district": "Quận 6", "aliases": ["Bình Tây", "Phường 2", "Phường 9", "Phường Bình Tây"]},
    "Phường Bình Tiên": {"district": "Quận 6", "aliases": ["Bình Tiên", "Phường 1", "Phường 7", "Phường 8", "Phường Bình Tiên"]},
    "Phường Bình Phú": {"district": "Quận 6", "aliases": ["Bình Phú", "Phường 10", "Phường 11", "Phường 16", "Phường Bình Phú"]},
    "Phường Phú Lâm": {"district": "Quận 6", "aliases": ["Phú Lâm", "Phường 12", "Phường 13", "Phường 14", "Phường Phú Lâm"]},
    "Phường Tân Thuận": {"district": "UNKNOWN_DISTRICT", "aliases": ["Bình Thuận", "Phường Tân Thuận", "Tân Thuận", "Tân Thuận Tây", "Tân Thuận Đông"]},
    "Phường Phú Thuận": {"district": "Quận 7", "aliases": ["Phú Mỹ", "Phú Thuận", "Phú Thuận", "Phường Phú Thuận"]},
    "Phường Tân Mỹ": {"district": "Quận 7", "aliases": ["Phú Mỹ", "Phường Tân Mỹ", "Tân Mỹ", "Tân Phú"]},
    "Phường Tân Hưng": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phường Tân Hưng", "Tân Hưng", "Tân Kiểng", "Tân Phong", "Tân Quy"]},
    "Phường Chánh Hưng": {"district": "Quận 8", "aliases": ["Chánh Hưng", "Hưng Phú", "Phường 4", "Phường 5", "Phường Chánh Hưng", "Rạch Ông"]},
    "Phường Phú Định": {"district": "Quận 8", "aliases": ["Phú Định", "Phường 14", "Phường 15", "Phường 16", "Phường Phú Định", "Xóm Củi"]},
    "Phường Bình Đông": {"district": "Quận 8", "aliases": ["Bình Đông", "Phường 5", "Phường 6", "Phường 7", "Phường Bình Đông", "xã An Phú Tây"]},
    "Phường Diên Hồng": {"district": "Quận 10", "aliases": ["Diên Hồng", "Phường 14", "Phường 6", "Phường 8", "Phường Diên Hồng"]},
    "Phường Vườn Lài": {"district": "Quận 10", "aliases": ["Phường 1", "Phường 10", "Phường 2", "Phường 4", "Phường 9", "Phường Vườn Lài", "Vườn Lài"]},
    "Phường Hòa Hưng": {"district": "Quận 10", "aliases": ["Hòa Hưng", "Phường 12", "Phường 13", "Phường 14", "Phường 15", "Phường Hòa Hưng"]},
    "Phường Minh Phụng": {"district": "Quận 11", "aliases": ["Minh Phụng", "Phường 1", "Phường 16", "Phường 7", "Phường Minh Phụng"]},
    "Phường Bình Thới": {"district": "Quận 11", "aliases": ["Bình Thới", "Phường 10", "Phường 3", "Phường 8", "Phường Bình Thới"]},
    "Phường Hòa Bình": {"district": "Quận 11", "aliases": ["Hòa Bình", "Phường 14", "Phường 5", "Phường Hòa Bình"]},
    "Phường Phú Thọ": {"district": "Quận 11", "aliases": ["Phú Thọ", "Phường 11", "Phường 15", "Phường 8", "Phường Phú Thọ"]},
    "Phường Đông Hưng Thuận": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phường Đông Hưng Thuận", "Tân Hưng Thuận", "Tân Thới Nhất", "Đông Hưng Thuận"]},
    "Phường Trung Mỹ Tây": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phường Trung Mỹ Tây", "Trung Mỹ Tây", "Tân Chánh Hiệp"]},
    "Phường Tân Thới Hiệp": {"district": "Quận 12", "aliases": ["Hiệp Thành", "Phường Tân Thới Hiệp", "Tân Thới Hiệp"]},
    "Phường Thới An": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phường Thới An", "Thạnh Xuân", "Thới An"]},
    "Phường An Phú Đông": {"district": "UNKNOWN_DISTRICT", "aliases": ["An Phú Đông", "Phường An Phú Đông", "Thạnh Lộc"]},
    "Phường An Lạc": {"district": "UNKNOWN_DISTRICT", "aliases": ["An Lạc", "An Lạc A", "Bình Trị Đông B", "Phường An Lạc"]},
    "Phường Bình Tân": {"district": "UNKNOWN_DISTRICT", "aliases": ["Bình Hưng Hòa B", "Bình Trị Đông A", "Bình Tân", "Phường Bình Tân", "Tân Tạo"]},
    "Phường Tân Tạo": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phường Tân Tạo", "Tân Kiên", "Tân Tạo", "Tân Tạo A"]},
    "Phường Bình Trị Đông": {"district": "UNKNOWN_DISTRICT", "aliases": ["Bình Hưng Hòa A", "Bình Trị Đông", "Bình Trị Đông A", "Phường Bình Trị Đông"]},
    "Phường Bình Hưng Hòa": {"district": "UNKNOWN_DISTRICT", "aliases": ["Bình Hưng Hòa", "Bình Hưng Hòa A", "Phường Bình Hưng Hòa", "Sơn Kỳ"]},
    "Phường Gia Định": {"district": "UNKNOWN_DISTRICT", "aliases": ["Gia Định", "Phường 1", "Phường 17", "Phường 2", "Phường 7", "Phường Gia Định"]},
    "Phường Bình Thạnh": {"district": "UNKNOWN_DISTRICT", "aliases": ["Bình Thạnh", "Phường 12", "Phường 14", "Phường 26", "Phường Bình Thạnh"]},
    "Phường Bình Lợi Trung": {"district": "UNKNOWN_DISTRICT", "aliases": ["Bình Lợi Trung", "Phường 11", "Phường 13", "Phường 5", "Phường Bình Lợi Trung"]},
    "Phường Thạnh Mỹ Tây": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phường 19", "Phường 22", "Phường 25", "Phường Thạnh Mỹ Tây", "Thạnh Mỹ Tây"]},
    "Phường Bình Quới": {"district": "UNKNOWN_DISTRICT", "aliases": ["Bình Quới", "Phường 27", "Phường 28", "Phường Bình Quới"]},
    "Phường Hạnh Thông": {"district": "UNKNOWN_DISTRICT", "aliases": ["Hạnh Thông", "Phường 1", "Phường 3", "Phường Hạnh Thông"]},
    "Phường An Nhơn": {"district": "UNKNOWN_DISTRICT", "aliases": ["An Nhơn", "Phường 5", "Phường 6", "Phường An Nhơn"]},
    "Phường Gò Vấp": {"district": "UNKNOWN_DISTRICT", "aliases": ["Gò Vấp", "Phường 10", "Phường 17", "Phường Gò Vấp"]},
    "Phường An Hội Đông": {"district": "UNKNOWN_DISTRICT", "aliases": ["An Hội Đông", "Phường 15", "Phường 16", "Phường An Hội Đông"]},
    "Phường Thông Tây Hội": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phường 11", "Phường 8", "Phường Thông Tây Hội", "Thông Tây Hội"]},
    "Phường An Hội Tây": {"district": "UNKNOWN_DISTRICT", "aliases": ["An Hội Tây", "Phường 12", "Phường 14", "Phường An Hội Tây"]},
    "Phường Đức Nhuận": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phường 4", "Phường 5", "Phường 9", "Phường Đức Nhuận", "Đức Nhuận"]},
    "Phường Cầu Kiệu": {"district": "UNKNOWN_DISTRICT", "aliases": ["Cầu Kiệu", "Phường 1", "Phường 15", "Phường 2", "Phường 7", "Phường Cầu Kiệu"]},
    "Phường Phú Nhuận": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phú Nhuận", "Phường 10", "Phường 11", "Phường 13", "Phường 15", "Phường 8", "Phường Phú Nhuận"]},
    "Phường Tân Sơn Hòa": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phường 1", "Phường 2", "Phường 3", "Phường Tân Sơn Hòa", "Tân Sơn Hòa"]},
    "Phường Tân Sơn Nhất": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phường 4", "Phường 5", "Phường 7", "Phường Tân Sơn Nhất", "Tân Sơn Nhất"]},
    "Phường Tân Hòa": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phường 6", "Phường 8", "Phường 9", "Phường Tân Hòa", "Tân Hòa"]},
    "Phường Bảy Hiền": {"district": "UNKNOWN_DISTRICT", "aliases": ["Bảy Hiền", "Phường 10", "Phường 11", "Phường 12", "Phường Bảy Hiền"]},
    "Phường Tân Bình": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phường 13", "Phường 14", "Phường 15", "Phường Tân Bình", "Tân Bình"]},
    "Phường Tân Sơn": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phường Tân Sơn", "Phần còn lại phường 15", "Tân Sơn"]},
    "Phường Tây Thạnh": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phường Tây Thạnh", "Sơn Kỳ", "Tây Thạnh"]},
    "Phường Tân Sơn Nhì": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phường Tân Sơn Nhì", "Sơn Kỳ", "Tân Quý", "Tân Sơn Nhì", "Tân Thành"]},
    "Phường Phú Thọ Hòa": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phú Thọ Hòa", "Phường Phú Thọ Hòa", "Tân Quý", "Tân Thành"]},
    "Phường Tân Phú": {"district": "UNKNOWN_DISTRICT", "aliases": ["Hòa Thạnh", "Phú Trung", "Phường Tân Phú", "Tân Phú", "Tân Thành", "Tân Thới Hòa"]},
    "Phường Phú Thạnh": {"district": "UNKNOWN_DISTRICT", "aliases": ["Hiệp Tân", "Phú Thạnh", "Phường Phú Thạnh", "Tân Thới Hòa"]},
    "Phường Hiệp Bình": {"district": "UNKNOWN_DISTRICT", "aliases": ["Hiệp Bình", "Hiệp Bình Chánh", "Hiệp Bình Phước", "Linh Đông", "Phường Hiệp Bình"]},
    "Phường Thủ Đức": {"district": "UNKNOWN_DISTRICT", "aliases": ["Bình Thọ", "Linh Chiểu", "Linh Tây", "Linh Đông", "Phường Thủ Đức", "Thủ Đức", "Trường Thọ"]},
    "Phường Tam Bình": {"district": "UNKNOWN_DISTRICT", "aliases": ["Bình Chiểu", "Phường Tam Bình", "Tam Bình", "Tam Phú"]},
    "Phường Linh Xuân": {"district": "UNKNOWN_DISTRICT", "aliases": ["Linh Trung", "Linh Tây", "Linh Xuân", "Phường Linh Xuân"]},
    "Phường Tăng Nhơn Phú": {"district": "UNKNOWN_DISTRICT", "aliases": ["Hiệp Phú", "Long Thạnh Mỹ", "Phường Tăng Nhơn Phú", "Tân Phú", "Tăng Nhơn Phú", "Tăng Nhơn Phú A", "Tăng Nhơn Phú B"]},
    "Phường Long Bình": {"district": "UNKNOWN_DISTRICT", "aliases": ["Long Bình", "Long Thạnh Mỹ", "Phường Long Bình"]},
    "Phường Long Phước": {"district": "UNKNOWN_DISTRICT", "aliases": ["Long Phước", "Phường Long Phước", "Trường Thạnh"]},
    "Phường Long Trường": {"district": "UNKNOWN_DISTRICT", "aliases": ["Long Trường", "Phú Hữu", "Phường Long Trường"]},
    "Phường Cát Lái": {"district": "UNKNOWN_DISTRICT", "aliases": ["Cát Lái", "Phường Cát Lái", "Thạnh Mỹ Lợi"]},
    "Phường Bình Trưng": {"district": "UNKNOWN_DISTRICT", "aliases": ["An Phú", "Bình Trưng", "Bình Trưng Tây", "Bình Trưng Đông", "Phường Bình Trưng"]},
    "Phường Phước Long": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phước Bình", "Phước Long", "Phước Long A", "Phước Long B", "Phường Phước Long"]},
    "Phường An Khánh": {"district": "UNKNOWN_DISTRICT", "aliases": ["An Khánh", "An Lợi Đông", "An Phú", "Phường An Khánh", "Thảo Điền", "Thủ Thiêm"]},
    "Xã Vĩnh Lộc": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phạm Văn Hai", "Vĩnh Lộc", "Vĩnh Lộc A", "Xã Vĩnh Lộc"]},
    "Xã Tân Vĩnh Lộc": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phạm Văn Hai", "Tân Tạo", "Tân Vĩnh Lộc", "Vĩnh Lộc B", "Xã Tân Vĩnh Lộc"]},
    "Xã Bình Lợi": {"district": "UNKNOWN_DISTRICT", "aliases": ["Bình Lợi", "Lê Minh Xuân", "Xã Bình Lợi"]},
    "Xã Tân Nhựt": {"district": "Quận 8", "aliases": ["Thị trấn Tân Túc", "Tân Nhựt", "Tân Tạo A", "Xã Tân Nhựt", "phường 16", "xã Tân Kiên"]},
    "Xã Bình Chánh": {"district": "UNKNOWN_DISTRICT", "aliases": ["An Phú Tây", "Bình Chánh", "Tân Quý Tây", "Xã Bình Chánh"]},
    "Xã Hưng Long": {"district": "UNKNOWN_DISTRICT", "aliases": ["Hưng Long", "Qui Đức", "Xã Hưng Long", "Đa Phước"]},
    "Xã Bình Hưng": {"district": "Quận 8", "aliases": ["Bình Hưng", "Phong Phú", "Phường 7", "Xã Bình Hưng", "xã Bình Hưng"]},
    "Xã Bình Khánh": {"district": "UNKNOWN_DISTRICT", "aliases": ["An Thới Đông", "Bình Khánh", "Tam Thôn Hiệp", "Xã Bình Khánh"]},
    "Xã An Thới Đông": {"district": "UNKNOWN_DISTRICT", "aliases": ["An Thới Đông", "Lý Nhơn", "Xã An Thới Đông"]},
    "Xã Cần Giờ": {"district": "UNKNOWN_DISTRICT", "aliases": ["Cần Giờ", "Long Hòa", "Thị trấn Cần Thạnh", "Xã Cần Giờ"]},
    "Xã Củ Chi": {"district": "UNKNOWN_DISTRICT", "aliases": ["Củ Chi", "Phước Vĩnh An", "Tân Phú Trung", "Tân Thông Hội", "Xã Củ Chi"]},
    "Xã Tân An Hội": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phước Hiệp", "Thị trấn Củ Chi", "Tân An Hội", "Xã Tân An Hội"]},
    "Xã Thái Mỹ": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phước Thạnh", "Thái Mỹ", "Trung Lập Thượng", "Xã Thái Mỹ"]},
    "Xã An Nhơn Tây": {"district": "UNKNOWN_DISTRICT", "aliases": ["An Nhơn Tây", "An Phú", "Phú Mỹ Hưng", "Xã An Nhơn Tây"]},
    "Xã Nhuận Đức": {"district": "UNKNOWN_DISTRICT", "aliases": ["Nhuận Đức", "Phạm Văn Cội", "Trung Lập Hạ", "Xã Nhuận Đức"]},
    "Xã Phú Hòa Đông": {"district": "UNKNOWN_DISTRICT", "aliases": ["Phú Hòa Đông", "Tân Thạnh Tây", "Tân Thạnh Đông", "Xã Phú Hòa Đông"]},
    "Xã Bình Mỹ": {"district": "UNKNOWN_DISTRICT", "aliases": ["Bình Mỹ", "Hòa Phú", "Trung An", "Xã Bình Mỹ"]},
    "Xã Đông Thạnh": {"district": "UNKNOWN_DISTRICT", "aliases": ["Nhị Bình", "Thới Tam Thôn", "Xã Đông Thạnh", "Đông Thạnh"]},
    "Xã Hóc Môn": {"district": "UNKNOWN_DISTRICT", "aliases": ["Hóc Môn", "Thị trấn Hóc Môn", "Tân Hiệp", "Tân Xuân", "Xã Hóc Môn"]},
    "Xã Xuân Thới Sơn": {"district": "UNKNOWN_DISTRICT", "aliases": ["Tân Thới Nhì", "Xuân Thới Sơn", "Xuân Thới Đông", "Xã Xuân Thới Sơn"]},
    "Xã Bà Điểm": {"district": "UNKNOWN_DISTRICT", "aliases": ["Bà Điểm", "Trung Chánh", "Xuân Thới Thượng", "Xã Bà Điểm"]},
    "Xã Nhà Bè": {"district": "UNKNOWN_DISTRICT", "aliases": ["Nhà Bè", "Phú Xuân", "Phước Kiển", "Phước Lộc", "Thị trấn Nhà Bè", "Xã Nhà Bè"]},
    "Xã Hiệp Phước": {"district": "UNKNOWN_DISTRICT", "aliases": ["Hiệp Phước", "Long Thới", "Nhơn Đức", "Xã Hiệp Phước"]},
}
